import json

# 第 1-50 個高品質單字對應表 (藍色等級)
enriched_data_blue_1 = {
    "postage": {"phonetic": "/ˈpoʊstɪdʒ/", "pos": "n.", "meaning": "郵資", "phrases": ["postage stamp", "postage paid"], "synonyms": ["mailing cost"], "antonyms": [], "example": "Please make sure you have the correct postage on the envelope before mailing it."},
    "prescription": {"phonetic": "/prɪˈskrɪpʃn/", "pos": "n.", "meaning": "處方箋", "phrases": ["prescription drug", "fill a prescription"], "synonyms": ["instruction", "remedy"], "antonyms": [], "example": "The doctor wrote a prescription for some antibiotics to treat the infection."},
    "press": {"phonetic": "/pres/", "pos": "n./v.", "meaning": "媒體；新聞界；按", "phrases": ["press conference", "press release"], "synonyms": ["media", "journalism"], "antonyms": [], "example": "The company held a press conference to announce its new product line."},
    "promotional": {"phonetic": "/prəˈmoʊʃənl/", "pos": "adj.", "meaning": "促銷的；宣傳的", "phrases": ["promotional material", "promotional campaign"], "synonyms": ["advertising"], "antonyms": [], "example": "We are distributing promotional leaflets in the city center to attract more customers."},
    "publication": {"phonetic": "/ˌpʌblɪˈkeɪʃn/", "pos": "n.", "meaning": "出版；刊物", "phrases": ["daily publication", "scientific publication"], "synonyms": ["issue", "printing"], "antonyms": [], "example": "The new book is scheduled for publication in early September."},
    "queue": {"phonetic": "/kjuː/", "pos": "n./v.", "meaning": "隊列；排隊", "phrases": ["stand in a queue", "jump the queue"], "synonyms": ["line"], "antonyms": [], "example": "There was a long queue of people waiting to buy tickets for the concert."},
    "railroad": {"phonetic": "/ˈreɪlroʊd/", "pos": "n.", "meaning": "鐵路", "phrases": ["railroad station", "railroad track"], "synonyms": ["railway"], "antonyms": [], "example": "The new railroad line will connect the two cities and reduce travel time."},
    "ranch": {"phonetic": "/ræntʃ/", "pos": "n.", "meaning": "大牧場；農場", "phrases": ["cattle ranch", "guest ranch"], "synonyms": ["farm", "estate"], "antonyms": [], "example": "He spent his summer working on a cattle ranch in the countryside."},
    "residence": {"phonetic": "/ˈrezɪdəns/", "pos": "n.", "meaning": "住宅；居住權", "phrases": ["permanent residence", "official residence"], "synonyms": ["home", "dwelling"], "antonyms": [], "example": "The ambassador's official residence is located near the city center."},
    "resident": {"phonetic": "/ˈrezɪdənt/", "pos": "n.", "meaning": "居民", "phrases": ["local resident", "permanent resident"], "synonyms": ["inhabitant", "citizen"], "antonyms": [], "example": "Local residents have complained about the noise from the nearby construction site."},
    "semester": {"phonetic": "/sɪˈmestər/", "pos": "n.", "meaning": "學期", "phrases": ["spring semester", "fall semester"], "synonyms": ["term"], "antonyms": [], "example": "The final exams will take place at the end of the fall semester."},
    "sneakers": {"phonetic": "/ˈsniːkərz/", "pos": "n.", "meaning": "運動鞋", "phrases": ["a pair of sneakers"], "synonyms": ["training shoes", "tennis shoes"], "antonyms": [], "example": "You should wear comfortable sneakers if you plan to go for a long walk."},
    "sick in mind and body": {"phonetic": "/sɪk ɪn maɪnd ænd ˈbɑːdi/", "pos": "adj.", "meaning": "身心疲憊", "phrases": [], "synonyms": ["exhausted"], "antonyms": ["healthy"], "example": "After working long hours for months, he felt sick in mind and body."},
    "society": {"phonetic": "/səˈsaɪəti/", "pos": "n.", "meaning": "社會；協會", "phrases": ["modern society", "professional society"], "synonyms": ["community", "association"], "antonyms": [], "example": "Technology has had a profound impact on all aspects of modern society."},
    "square": {"phonetic": "/skwer/", "pos": "n./adj.", "meaning": "廣場；正方形的", "phrases": ["town square", "square meter"], "synonyms": ["plaza"], "antonyms": [], "example": "The city's main square is a popular gathering place for locals and tourists."},
    "stable": {"phonetic": "/ˈsteɪbl/", "pos": "adj./n.", "meaning": "穩定的；馬廄", "phrases": ["stable condition", "stable price"], "synonyms": ["steady", "firm"], "antonyms": ["unstable", "shaky"], "example": "The company's financial situation has remained stable over the last few years."},
    "suit": {"phonetic": "/suːt/", "pos": "n./v.", "meaning": "西裝；適合", "phrases": ["business suit", "lawsuit"], "synonyms": ["outfit", "fit"], "antonyms": [], "example": "The candidate wore a dark blue suit for his job interview."},
    "suitcase": {"phonetic": "/ˈsuːtkeɪs/", "pos": "n.", "meaning": "手提箱；行李箱", "phrases": ["pack a suitcase", "heavy suitcase"], "synonyms": ["bag", "luggage"], "antonyms": [], "example": "She packed her suitcase and headed to the airport for her vacation."},
    "tailor": {"phonetic": "/ˈteɪlər/", "pos": "n./v.", "meaning": "裁縫；量身打造", "phrases": ["tailor-made", "professional tailor"], "synonyms": ["adjust", "customize"], "antonyms": [], "example": "The training program was tailored to meet the specific needs of our employees."},
    "terminal": {"phonetic": "/ˈtɜːrmɪnl/", "pos": "n./adj.", "meaning": "航站；終端機；晚期的", "phrases": ["airport terminal", "computer terminal"], "synonyms": ["station", "end"], "antonyms": [], "example": "Please proceed to terminal two for all international flight departures."},
    "tenant": {"phonetic": "/ˈtenənt/", "pos": "n.", "meaning": "租戶；房客", "phrases": ["new tenant", "sitting tenant"], "synonyms": ["lessee", "occupant"], "antonyms": ["landlord"], "example": "The landlord is looking for a new tenant to rent the vacant apartment."},
    "toll": {"phonetic": "/toʊl/", "pos": "n.", "meaning": "通行費；代價", "phrases": ["toll road", "toll bridge"], "synonyms": ["fee", "charge"], "antonyms": [], "example": "You have to pay a toll to cross the bridge into the city center."},
    "tour": {"phonetic": "/tʊr/", "pos": "n./v.", "meaning": "導覽；旅遊", "phrases": ["guided tour", "business tour"], "synonyms": ["trip", "excursion"], "antonyms": [], "example": "We took a guided tour of the factory to see how the products are made."},
    "track": {"phonetic": "/træk/", "pos": "n./v.", "meaning": "軌道；追蹤", "phrases": ["keep track of", "on track"], "synonyms": ["path", "monitor"], "antonyms": [], "example": "It's important to keep track of all your business expenses for tax purposes."},
    "traditional": {"phonetic": "/trəˈdɪʃənl/", "pos": "adj.", "meaning": "傳統的", "phrases": ["traditional values", "traditional method"], "synonyms": ["conventional", "customary"], "antonyms": ["modern", "innovative"], "example": "The company still uses some traditional methods of production alongside new technology."},
    "unsanitary": {"phonetic": "/ʌnˈsænɪteri/", "pos": "adj.", "meaning": "不衛生的", "phrases": ["unsanitary conditions"], "synonyms": ["unhygienic", "dirty"], "antonyms": ["sanitary", "clean"], "example": "The restaurant was closed down due to its extremely unsanitary kitchen conditions."},
    "vaccinate": {"phonetic": "/ˈvæksɪneɪt/", "pos": "v.", "meaning": "接種疫苗", "phrases": ["get vaccinated"], "synonyms": ["immunize"], "antonyms": [], "example": "It is recommended that all international travelers be vaccinated against certain diseases."},
    "vegetarian": {"phonetic": "/ˌvedʒəˈteriən/", "pos": "n./adj.", "meaning": "素食者；素食的", "phrases": ["vegetarian meal", "strict vegetarian"], "synonyms": [], "antonyms": [], "example": "The restaurant offers a variety of delicious vegetarian dishes on its menu."},
    "vehicle": {"phonetic": "/ˈviːəkl/", "pos": "n.", "meaning": "車輛；工具", "phrases": ["motor vehicle", "commercial vehicle"], "synonyms": ["car", "conveyance"], "antonyms": [], "example": "All commercial vehicles must be registered with the local transportation authority."},
    "vending machine": {"phonetic": "/ˈvendɪŋ məˈʃiːn/", "pos": "n.", "meaning": "販賣機", "phrases": ["beverage vending machine"], "synonyms": [], "antonyms": [], "example": "You can get cold drinks and snacks from the vending machine in the lobby."},
    "voyage": {"phonetic": "/ˈvɔɪɪdʒ/", "pos": "n./v.", "meaning": "航程；旅程", "phrases": ["maiden voyage", "sea voyage"], "synonyms": ["journey", "trip"], "antonyms": [], "example": "The ship is preparing for its maiden voyage across the Atlantic Ocean."},
    "spy": {"phonetic": "/spaɪ/", "pos": "n./v.", "meaning": "間諜；暗中監視", "phrases": ["industrial spy", "spy on"], "synonyms": ["secret agent", "monitor"], "antonyms": [], "example": "The company was accused of hiring an industrial spy to steal its competitor's secrets."},
    "stack": {"phonetic": "/stæk/", "pos": "n./v.", "meaning": "疊；堆", "phrases": ["a stack of paper", "stack the boxes"], "synonyms": ["pile", "heap"], "antonyms": [], "example": "Please place the new files in the stack on the corner of my desk."},
    "strive": {"phonetic": "/straɪv/", "pos": "v.", "meaning": "努力；奮鬥", "phrases": ["strive for success", "strive to do"], "synonyms": ["endeavor", "attempt"], "antonyms": ["give up"], "example": "Our company strives to provide the highest quality of service to our customers."},
    "structure": {"phonetic": "/ˈstrʌktʃər/", "pos": "n./v.", "meaning": "結構；建築物", "phrases": ["organizational structure", "social structure"], "synonyms": ["framework", "organization"], "antonyms": [], "example": "The company is planning to change its organizational structure to improve efficiency."},
    "substantiate": {"phonetic": "/səbˈstænʃieɪt/", "pos": "v.", "meaning": "證實", "phrases": ["substantiate a claim", "fully substantiate"], "synonyms": ["verify", "confirm"], "antonyms": ["disprove", "refute"], "example": "You need to provide some evidence to substantiate your claims against the manager."},
    "support": {"phonetic": "/səˈpɔːrt/", "pos": "v./n.", "meaning": "支持；擁護", "phrases": ["technical support", "customer support"], "synonyms": ["assist", "aid"], "antonyms": ["oppose", "hinder"], "example": "Please contact our technical support team if you have any problems with the software."},
    "suppose": {"phonetic": "/səˈpoʊz/", "pos": "v.", "meaning": "猜想；假設", "phrases": ["be supposed to", "supposedly"], "synonyms": ["assume", "think"], "antonyms": [], "example": "I suppose that the meeting will take place in the conference room as usual."},
    "surmize": {"phonetic": "/sərˈmaɪz/", "pos": "v./n.", "meaning": "推測；猜度", "phrases": [], "synonyms": ["guess", "conjecture"], "antonyms": [], "example": "We can only surmize that the drop in sales was due to the recent price increase."},
    "survey": {"phonetic": "/ˈsɜːrveɪ/", "pos": "n./v.", "meaning": "調查；測量", "phrases": ["customer survey", "conduct a survey"], "synonyms": ["poll", "study"], "antonyms": [], "example": "According to a recent customer survey, most people are happy with our new products."},
    "survive": {"phonetic": "/sərˈvaɪv/", "pos": "v.", "meaning": "倖存；活下來", "phrases": ["survive the crisis", "survival rate"], "synonyms": ["endure", "persist"], "antonyms": ["die", "perish"], "example": "Few businesses were able to survive the severe economic crisis last year."},
    "sustain": {"phonetic": "/səˈsteɪn/", "pos": "v.", "meaning": "維持；遭受(損失)", "phrases": ["sustain growth", "sustain a loss"], "synonyms": ["maintain", "undergo"], "antonyms": ["end", "stop"], "example": "The company has managed to sustain a high level of growth over the last five years."},
    "swap": {"phonetic": "/swɑːp/", "pos": "v./n.", "meaning": "交換", "phrases": ["swap ideas", "swap places"], "synonyms": ["exchange", "trade"], "antonyms": [], "example": "I'd like to swap my morning shift for your afternoon shift next Tuesday."},
    "sway": {"phonetic": "/sweɪ/", "pos": "v./n.", "meaning": "搖擺；影響", "phrases": ["hold sway", "sway public opinion"], "synonyms": ["influence", "persuade"], "antonyms": [], "example": "The manager's persuasive arguments were able to sway the board's decision."},
    "temper": {"phonetic": "/ˈtempər/", "pos": "n./v.", "meaning": "脾氣；調和", "phrases": ["lose one's temper", "bad temper"], "synonyms": ["mood", "disposition"], "antonyms": [], "example": "It is important to keep your temper even when dealing with difficult customers."},
    "testify": {"phonetic": "/ˈtestɪfaɪ/", "pos": "v.", "meaning": "作證；證實", "phrases": ["testify against", "testify to"], "synonyms": ["bear witness", "certify"], "antonyms": [], "example": "Several witnesses were called to testify during the court case last week."},
    "thrive": {"phonetic": "/θraɪv/", "pos": "v.", "meaning": "繁榮；興旺", "phrases": ["thrive on competition", "thriving business"], "synonyms": ["prosper", "flourish"], "antonyms": ["fail", "decline"], "example": "The local tourism industry has continued to thrive despite the economic downturn."},
    "transcend": {"phonetic": "/trænˈsend/", "pos": "v.", "meaning": "超越；凌駕", "phrases": ["transcend boundaries", "transcend limitations"], "synonyms": ["surpass", "exceed"], "antonyms": [], "example": "His innovative ideas transcend the traditional boundaries of the industry."},
    "underline": {"phonetic": "/ˌʌndərˈlaɪn/", "pos": "v.", "meaning": "畫底線；強調", "phrases": [], "synonyms": ["emphasize", "highlight"], "antonyms": [], "example": "The manager wanted to underline the importance of meeting the project deadline."},
    "unveil": {"phonetic": "/ˌʌnˈveɪl/", "pos": "v.", "meaning": "揭幕；公開", "phrases": ["unveil a statue", "unveil a plan"], "synonyms": ["reveal", "disclose"], "antonyms": ["hide", "conceal"], "example": "The company is planning to unveil its new marketing strategy next month."}
}

with open('data_blue.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

for item in data:
    word = item['word']
    if word in enriched_data_blue_1:
        item.update(enriched_data_blue_1[word])

with open('data_blue.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print("成功精修藍色等級第 1-50 個高品質單字。")
