import json

# 第 151-200 個高品質單字對應表 (藍色等級)
enriched_data_blue_4 = {
    "pioneer": {"phonetic": "/ˌpaɪəˈnɪr/", "pos": "n./v.", "meaning": "先驅；開創", "phrases": ["pioneer in"], "synonyms": ["innovator", "trailblazer"], "antonyms": ["follower"], "example": "The company is a pioneer in the field of renewable energy and has many patents."},
    "ponder": {"phonetic": "/ˈpɑːndər/", "pos": "v.", "meaning": "沉思；仔細考慮", "phrases": ["ponder over"], "synonyms": ["consider", "contemplate"], "antonyms": ["ignore"], "example": "The manager took some time to ponder the proposal before giving his final approval."},
    "precondition": {"phonetic": "/ˌpriːkənˈdɪʃn/", "pos": "n.", "meaning": "前提條件", "phrases": ["essential precondition"], "synonyms": ["prerequisite"], "antonyms": [], "example": "Having a valid business license is a precondition for applying for the government grant."},
    "predominate": {"phonetic": "/prɪˈdɑːmɪneɪt/", "pos": "v.", "meaning": "佔優勢；主導", "phrases": [], "synonyms": ["dominate", "prevail"], "antonyms": [], "example": "Our products currently predominate in the local market, but competition is increasing."},
    "preempt": {"phonetic": "/priˈempt/", "pos": "v.", "meaning": "先發制人；取代", "phrases": ["preemptive strike"], "synonyms": ["forestall", "preclude"], "antonyms": [], "example": "The news broadcast was preempted by a special announcement from the president."},
    "proliferate": {"phonetic": "/prəˈlɪfəreɪt/", "pos": "v.", "meaning": "激增；擴散", "phrases": ["proliferate rapidly"], "synonyms": ["multiply", "expand"], "antonyms": ["decrease", "stagnate"], "example": "Fast food restaurants have continued to proliferate in the city center over the last decade."},
    "prolong": {"phonetic": "/prəˈlɔːŋ/", "pos": "v.", "meaning": "延長", "phrases": ["prolong life"], "synonyms": ["extend", "lengthen"], "antonyms": ["shorten", "curtail"], "example": "The meeting was prolonged by several hours due to the intense discussion about the budget."},
    "riterate": {"word": "reiterate", "phonetic": "/riˈɪtəreɪt/", "pos": "v.", "meaning": "重申；反覆說", "phrases": ["reiterate a point"], "synonyms": ["repeat", "restate"], "antonyms": [], "example": "I would like to reiterate that all employees must follow the new safety regulations."},
    "relinquish": {"phonetic": "/rɪˈlɪŋkwɪʃ/", "pos": "v.", "meaning": "放棄；交出", "phrases": ["relinquish control"], "synonyms": ["abandon", "surrender"], "antonyms": ["retain", "keep"], "example": "He was forced to relinquish his position as CEO after the company's financial scandal."},
    "remit": {"phonetic": "/rɪˈmɪt/", "pos": "v./n.", "meaning": "匯款；豁免", "phrases": ["remit payment"], "synonyms": ["send", "forward"], "antonyms": [], "example": "Please remit the payment to our bank account by the end of the month."},
    "scrutinize": {"phonetic": "/ˈskruːtənaɪz/", "pos": "v.", "meaning": "詳察；仔細檢查", "phrases": ["scrutinize data"], "synonyms": ["examine", "inspect"], "antonyms": ["glance", "overlook"], "example": "The auditors will scrutinize the company's financial records for any inconsistencies."},
    "slander": {"phonetic": "/ˈslændər/", "pos": "n./v.", "meaning": "誹謗；詆毀", "phrases": ["slanderous remarks"], "synonyms": ["defamation", "vilification"], "antonyms": ["praise", "compliment"], "example": "The company filed a lawsuit for slander after the competitor made false claims about its products."},
    "tackle": {"phonetic": "/ˈtækl/", "pos": "v./n.", "meaning": "處理；應對", "phrases": ["tackle a problem"], "synonyms": ["handle", "address"], "antonyms": ["avoid", "neglect"], "example": "The government is planning new measures to tackle the problem of youth unemployment."},
    "instinctively": {"phonetic": "/ɪnˈstɪŋktɪvli/", "pos": "adv.", "meaning": "本能地；直覺地", "phrases": [], "synonyms": ["naturally", "intuitively"], "antonyms": ["deliberately"], "example": "He instinctively knew that something was wrong when he saw the empty office."},
    "intensive": {"phonetic": "/ɪnˈtensɪv/", "pos": "adj.", "meaning": "密集的；徹底的", "phrases": ["intensive care", "intensive training"], "synonyms": ["thorough", "concentrated"], "antonyms": ["superficial"], "example": "New employees are required to undergo a week of intensive training before they start work."},
    "intent": {"phonetic": "/ɪnˈtent/", "pos": "n./adj.", "meaning": "意圖；專注的", "phrases": ["clear intent", "intent on doing"], "synonyms": ["purpose", "aim"], "antonyms": [], "example": "The company's clear intent is to become the market leader in the next three years."},
    "interchangeable": {"phonetic": "/ˌɪntərˈtʃeɪndʒəbl/", "pos": "adj.", "meaning": "可互換的", "phrases": ["interchangeable parts"], "synonyms": ["exchangeable", "equivalent"], "antonyms": ["unique", "specific"], "example": "These two spare parts are interchangeable and can be used in either model of the machine."},
    "interim": {"phonetic": "/ˈɪntərɪm/", "pos": "adj./n.", "meaning": "暫時的；中期", "phrases": ["interim report", "interim manager"], "synonyms": ["temporary", "provisional"], "antonyms": ["permanent"], "example": "An interim manager was appointed to lead the department until a permanent replacement is found."},
    "intermittent": {"phonetic": "/ˌɪntərˈmɪtənt/", "pos": "adj.", "meaning": "間歇的；斷斷續續的", "phrases": ["intermittent power failure"], "synonyms": ["sporadic", "occasional"], "antonyms": ["constant", "continuous"], "example": "The region has been experiencing intermittent power failures due to the severe weather."},
    "intricate": {"phonetic": "/ˈintrikət/", "pos": "adj.", "meaning": "複雜的；精緻的", "phrases": ["intricate design"], "synonyms": ["complex", "elaborate"], "antonyms": ["simple", "plain"], "example": "The new watch design features an intricate mechanism with hundreds of tiny parts."},
    "legitimate": {"phonetic": "/ləˈdʒɪtɪmət/", "pos": "adj./v.", "meaning": "合法的；正當的", "phrases": ["legitimate concern"], "synonyms": ["legal", "valid"], "antonyms": ["illegal", "invalid"], "example": "The company has a legitimate reason for wanting to terminate the contract."},
    "liable": {"phonetic": "/ˈlaɪəbl/", "pos": "adj.", "meaning": "法律上負責的；易於...的", "phrases": ["be liable for"], "synonyms": ["responsible", "accountable"], "antonyms": [], "example": "You will be held liable for any damage caused to the equipment while it is in your care."},
    "maternal": {"phonetic": "/məˈtɜːrnl/", "pos": "adj.", "meaning": "母親的；母性的", "phrases": ["maternal leave"], "synonyms": [], "antonyms": ["paternal"], "example": "The company offers six months of paid maternal leave to its female employees."},
    "mediocre": {"phonetic": "/ˌmiːdiˈoʊkər/", "pos": "adj.", "meaning": "平庸的；二流的", "phrases": [], "synonyms": ["average", "ordinary"], "antonyms": ["excellent", "superior"], "example": "The restaurant received a mediocre review from the food critic for its uninspiring menu."},
    "meticulous": {"phonetic": "/məˈtɪkjələs/", "pos": "adj.", "meaning": "嚴謹的；一絲不苟的", "phrases": ["meticulous attention to detail"], "synonyms": ["thorough", "careful"], "antonyms": ["careless", "sloppy"], "example": "He is a meticulous researcher who always checks his data multiple times."},
    "myriad": {"phonetic": "/ˈmɪriəd/", "pos": "n./adj.", "meaning": "無數的；大量", "phrases": ["a myriad of"], "synonyms": ["countless", "innumerable"], "antonyms": ["few", "scarce"], "example": "There are a myriad of factors to consider before making a decision about the merger."},
    "opportune": {"phonetic": "/ˌɑːpərˈtuːn/", "pos": "adj.", "meaning": "湊巧的；適切的", "phrases": ["opportune moment"], "synonyms": ["timely", "appropriate"], "antonyms": ["inopportune"], "example": "The sudden drop in interest rates provided an opportune moment for the company to expand."},
    "ostensibly": {"phonetic": "/ɑːˈstensəbli/", "pos": "adv.", "meaning": "表面上地；假裝地", "phrases": [], "synonyms": ["apparently", "seemingly"], "antonyms": [], "example": "He resigned ostensibly for health reasons, but many believe there were other factors involved."},
    "paramount": {"phonetic": "/ˈpærəmaʊnt/", "pos": "adj.", "meaning": "首要的；至高無上的", "phrases": ["paramount importance"], "synonyms": ["supreme", "primary"], "antonyms": ["secondary"], "example": "The safety of our employees is of paramount importance to the company."},
    "peculiar": {"phonetic": "/pɪˈkjuːliər/", "pos": "adj.", "meaning": "特別的；古怪的", "phrases": ["peculiar behavior"], "synonyms": ["odd", "strange"], "antonyms": ["normal", "common"], "example": "The machine was making a peculiar noise, so we called the maintenance team to check it."},
    "perennial": {"phonetic": "/pəˈreniəl/", "pos": "adj./n.", "meaning": "終年的；長期的", "phrases": ["perennial problem"], "synonyms": ["enduring", "lasting"], "antonyms": ["temporary"], "example": "Finding enough skilled workers is a perennial problem for many companies in the industry."},
    "placid": {"phonetic": "/ˈplæsɪd/", "pos": "adj.", "meaning": "平靜的；寧靜的", "phrases": ["placid lake"], "synonyms": ["calm", "peaceful"], "antonyms": ["turbulent", "agitated"], "example": "The lake was calm and placid in the early morning sunlight."},
    "pertinent": {"phonetic": "/ˈpɜːrtnənt/", "pos": "adj.", "meaning": "相關的；中肯的", "phrases": ["pertinent question"], "synonyms": ["relevant", "applicable"], "antonyms": ["irrelevant"], "example": "Please provide all pertinent information regarding your previous work experience."},
    "plain": {"phonetic": "/pleɪn/", "pos": "adj./n.", "meaning": "明白的；樸素的", "phrases": ["plain English", "make it plain"], "synonyms": ["simple", "clear"], "antonyms": ["complex", "elaborate"], "example": "The instructions were written in plain English so that everyone could understand them."},
    "portable": {"phonetic": "/ˈpɔːrtəbl/", "pos": "adj./n.", "meaning": "手提式的；可攜帶的", "phrases": ["portable device"], "synonyms": ["handy", "mobile"], "antonyms": ["fixed", "stationary"], "example": "The new laptop is lightweight and portable, making it perfect for business travel."},
    "pretentious": {"phonetic": "/prɪˈtenʃəs/", "pos": "adj.", "meaning": "自命不凡的；虛飾的", "phrases": [], "synonyms": ["showy", "pompous"], "antonyms": ["humble", "modest"], "example": "The new restaurant was criticized for its pretentious atmosphere and overpriced menu."},
    "prolific": {"phonetic": "/prəˈlɪfɪk/", "pos": "adj.", "meaning": "多產的；豐富的", "phrases": ["prolific writer"], "synonyms": ["productive", "fruitful"], "antonyms": ["unproductive"], "example": "He is a prolific writer who has published more than twenty books in the last ten years."},
    "prosaic": {"phonetic": "/prəˈzeɪɪk/", "pos": "adj.", "meaning": "平凡的；乏味的", "phrases": [], "synonyms": ["mundane", "ordinary"], "antonyms": ["extraordinary", "imaginative"], "example": "Despite the exciting headlines, the actual results of the research were quite prosaic."},
    "pushy": {"phonetic": "/ˈpʊʃi/", "pos": "adj.", "meaning": "咄咄逼人的；愛強求的", "phrases": ["pushy salesperson"], "synonyms": ["assertive", "aggressive"], "antonyms": ["passive", "timid"], "example": "Customers often complain about the pushy sales tactics used by some of the staff."},
    "reticent": {"phonetic": "/ˈretɪsnt/", "pos": "adj.", "meaning": "沉默寡言的；謹慎的", "phrases": ["be reticent about"], "synonyms": ["reserved", "quiet"], "antonyms": ["talkative", "open"], "example": "The manager was reticent about the company's future plans during the press conference."},
    "residual": {"phonetic": "/rɪˈzɪdʒuəl/", "pos": "adj./n.", "meaning": "剩餘的；殘留的", "phrases": ["residual income"], "synonyms": ["remaining", "leftover"], "antonyms": [], "example": "The company still earns residual income from the patents it sold several years ago."},
    "rotten": {"phonetic": "/ˈrɑːtn/", "pos": "adj.", "meaning": "腐爛的；極糟的", "phrases": [], "synonyms": ["decaying", "bad"], "antonyms": ["fresh"], "example": "The smell from the kitchen was horrible due to some rotten vegetables in the bin."},
    "salient": {"phonetic": "/ˈseɪliənt/", "pos": "adj.", "meaning": "顯著的；主要的", "phrases": ["salient point"], "synonyms": ["prominent", "conspicuous"], "antonyms": ["insignificant"], "example": "The report highlights the salient features of the new marketing strategy."},
    "scatterbrained": {"phonetic": "/ˈskætərbreɪnd/", "pos": "adj.", "meaning": "沒頭腦的；注意力不集中的", "phrases": [], "synonyms": ["forgetful", "absent-minded"], "antonyms": ["focused", "attentive"], "example": "She is a bit scatterbrained and often forgets where she put her office keys."},
    "scrupulous": {"phonetic": "/ˈskruːpjələs/", "pos": "adj.", "meaning": "嚴謹的；誠實的", "phrases": ["scrupulous adherence"], "synonyms": ["meticulous", "honest"], "antonyms": ["unscrupulous", "careless"], "example": "The company is known for its scrupulous adherence to ethical business practices."},
    "seamlessly": {"phonetic": "/ˈsiːmləsli/", "pos": "adv.", "meaning": "無縫地；順暢地", "phrases": ["integrate seamlessly"], "synonyms": ["smoothly"], "antonyms": [], "example": "The new software was designed to integrate seamlessly with the existing computer system."},
    "slantwise": {"phonetic": "/ˈslæntwaɪz/", "pos": "adv./adj.", "meaning": "傾斜地", "phrases": [], "synonyms": ["obliquely", "diagonally"], "antonyms": ["straight"], "example": "The light from the window fell slantwise across the desk in the late afternoon."},
    "somber": {"phonetic": "/ˈsɑːmbər/", "pos": "adj.", "meaning": "陰沉的；憂鬱的", "phrases": ["somber mood"], "synonyms": ["gloomy", "serious"], "antonyms": ["cheerful", "bright"], "example": "The CEO's somber tone during the meeting suggested that bad news was coming."},
    "steadfast": {"phonetic": "/ˈstedfæst/", "pos": "adj.", "meaning": "堅定的；不動搖的", "phrases": ["steadfast support"], "synonyms": ["loyal", "firm"], "antonyms": ["fickle", "unreliable"], "example": "We are grateful for your steadfast support during the company's difficult transition period."},
    "stationary": {"phonetic": "/ˈsteɪʃəneri/", "pos": "adj.", "meaning": "靜止的；不動的", "phrases": ["stationary vehicle"], "synonyms": ["motionless", "fixed"], "antonyms": ["moving", "mobile"], "example": "The truck remained stationary for several hours while the workers loaded the cargo."}
}

with open('data_blue.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

for item in data:
    word = item['word']
    if word in enriched_data_blue_4:
        update_info = enriched_data_blue_4[word].copy()
        if 'word' in update_info:
            item['word'] = update_info.pop('word')
        item.update(update_info)

with open('data_blue.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print("成功精修藍色等級第 151-200 個單字，並修正拼寫與翻譯錯誤。")
